// Full Spotify catalog, grouped by album. Auto-generated for the /curate page.
export type CatalogTrack = { title: string; id: string };
export type CatalogAlbum = { album: string; albumId: string; tracks: CatalogTrack[] };

export const CATALOG: CatalogAlbum[] = [
  {
    album: "The World Is Everything That Is the Case",
    albumId: "6jg4Lc1foJRFO4NAWM9w2Y",
    tracks: [
      { title: "Games of Language", id: "10bu7GMzpBKKnbTTzpkYKW" },
      { title: "Sitting by the Beach", id: "1Xy7aDhD9ZbCi844Dtabdh" },
      { title: "The Moon", id: "2LA84zJahu2b58M8dOByYD" },
      { title: "Friendship Is Magic", id: "4YTPdnKcJUYvtaVYT0yUxo" },
      { title: "Water's Mist", id: "32VX116l1xPhIqs8zEgOx4" },
      { title: "Logical Picture", id: "47N23nEj98BIIzy13RHEXR" },
      { title: "Don't Close Your Eyes", id: "1GaEWBUQKzQUbg5vR17POB" },
      { title: "2010 Honda Accord", id: "48yXcTelXzpSRbsi9weMvD" },
      { title: "Rouick", id: "6l9HadzdXz6CBjB7Ctv2ys" },
      { title: "Whereof One Cannot Speak Thereof One Must Be Silent", id: "77M3acOPzNwG1vS0EV7cky" },
    ],
  },
  {
    album: "Tritone Substitutions",
    albumId: "2K76bn4iZrqsrhdi8Rr6B3",
    tracks: [
      { title: "End of the Beginning", id: "2A6VRLTF7eTgMGkTpXRAGJ" },
      { title: "A Sky of Sunflowers", id: "03eAYIsayEKyI5hPR4hCqO" },
      { title: "Turquoise", id: "6i6nCINFS30E75PuuYKtoL" },
      { title: "Crab Cafe", id: "2QtySsVTM9jB8rRjBN6Yjg" },
      { title: "Liminal Spaces", id: "0JyxG3QY40E7NRXwQOupqa" },
      { title: "Running from Fate", id: "5jd1WCfdkO26nQnjskje1S" },
      { title: "Singularity", id: "141pOMKQbCSsXGk8tDPbmR" },
      { title: "Circuit", id: "5n9gOX7jMbSBacAUasPII9" },
      { title: "Hollow Chambers", id: "4pRwkvStQ7l80Wwa5lcwJk" },
      { title: "Mechanical Breathing", id: "0clAtMagxRYSgckfm2GQK2" },
      { title: "The Underground Is Alive", id: "42Z2gxD75XqNRR3SiGNjDY" },
      { title: "The Fibonacci Sequences", id: "3EatbeaRuaavy1E2YEVyed" },
    ],
  },
  {
    album: "Sounds from Desmos",
    albumId: "1goaHGnOcNDo3MwVSoVL26",
    tracks: [
      { title: "Desmos Sounds Like a Church Organ...", id: "0qoGSoAsSDo29dyWBfsdtC" },
      { title: "Making Beats in Desmos", id: "44zIsnTmUvWcVrY0vmYZKv" },
      { title: "Megolovainia in Desmos", id: "4LHXqID1zi74ClT7YVKUxh" },
      { title: "Desmos Is Officially an Instrument", id: "70JdCf49sezZw9M8At8Xk2" },
      { title: "Desmos Is the Best Daw...", id: "7I6jrm100AaQwXPeYjL7p2" },
      { title: "Additive Synthesis Is Addictive...", id: "2UI9jdcFhmDTbHgzi9CnUH" },
      { title: "Desmos Is a New Genre of Music...", id: "2pfQYhS4BmvKTDT2JX952r" },
      { title: "Math Rock", id: "4YfCXtyrm6R69g7Q1bFGgL" },
      { title: "Desmos Sounds Like the Minecraft Ost...", id: "2caj5jIKLJPATrvZKVQkFn" },
      { title: "Wait Desmos Actually Slaps", id: "2wDK3zh3b9cNSvMS0lYnb4" },
      { title: "Please Help Me I'm Addicted", id: "0LoXadEua9Vtahyk9lY6Z8" },
      { title: "Desmos Is Beautiful...", id: "3F0QLsm8HL7TSsi53P8WcC" },
    ],
  },
  {
    album: "Inversions",
    albumId: "2inRax2rgIDCjQoshl2Wei",
    tracks: [
      { title: "Deciduous Daydream", id: "32kVg4QvAKFQ1aYTwIZFNp" },
      { title: "TrEs 2b", id: "5TcAQWJbDKkEs0nCKjn0Lk" },
      { title: "Wreck of the World", id: "6J6G1eul9K1mFacduPwZIo" },
      { title: "Lightyear", id: "3jCAHUTFghZiEpm7yhRKuI" },
      { title: "I Thought It Was Real", id: "1ezjgiD2AQPkAPTGRvffQg" },
      { title: "C4 H10 F O2 P", id: "5BaJCGweZpZP0JFOmUt60y" },
    ],
  },
  {
    album: "Stages of Grief",
    albumId: "12fEWa8fymUpsizZcEjmw9",
    tracks: [
      { title: "Ignorance Is Bliss", id: "7yqD2p6znkwWUC4s0FnU6r" },
      { title: "The Storm Arrives", id: "3edKmjJ28TikWXZFhlYbG7" },
      { title: "Please Pick Up", id: "4X3HdyjLBWT0rklixQJosq" },
      { title: "Lights Are Out", id: "2j2O1DdN0qk2VlJCkuax1O" },
      { title: "Your Fault", id: "5Wg0F11Bx6QqAtiGa7TpqD" },
      { title: "Something in My Head", id: "6X65NOQ41X3QJ0aMrb8PbB" },
      { title: "My Fault", id: "7DSybdQDjYQhoOq83Ky5LK" },
      { title: "Emptiness, Pt. 1", id: "2gtqQSTGHLOQ3XdovJx67V" },
      { title: "Emptiness, Pt. 2", id: "6cDunmQN3zgdMe4YLuTzHQ" },
      { title: "Dried Up", id: "4DFbk95cVZXSpLd0PD8fCm" },
      { title: "Empty Bliss", id: "4gfEyeeGfJEcTbV9KXdfQo" },
      { title: "Gone, Gone.", id: "3gwdvRaJuPVgaaNzmQ4SB9" },
      { title: "Still the Sun", id: "3PPnPk8XBgiGXOsN5apqG4" },
      { title: "The End", id: "16jX6p4Q11it0TI3YuJgUU" },
      { title: "Emptiness Pt. 3", id: "04eCpMVToIGNlRQQJ9elQ8" },
      { title: "Isolation of the Mind", id: "17oLIE2gIZni8GDxfmDgev" },
      { title: "Hallucinations", id: "4hVJUBDGgvGGa6FktWjup6" },
      { title: "Loss of Purpose", id: "2sQ7ytR8N3x5st2tk55eFK" },
      { title: "Sounds from the Brink", id: "5fwrngeOykpl0quaV8W3hD" },
      { title: "The End, Again.", id: "6LbdRUTFxEh5ZZy8oDqerS" },
      { title: "Bye Bye", id: "2rsaBoDa5WXoXQ5wHu9IIX" },
    ],
  },
  {
    album: "Piano Medley for Fall",
    albumId: "0fYeaC8FgXMIwd9ndsWFTM",
    tracks: [
      { title: "A Breath of Fresh Air", id: "6tZoXOwI4fvYaohrTPxN80" },
      { title: "The Leaves Are Changing...", id: "5B5SIiukWLJAzJ4fOgJscZ" },
      { title: "Cycle of Life", id: "2IKE2AiDFx5M3zPnXPELzQ" },
      { title: "Kinda Reminds Me of Snowdin Town Song...", id: "2XsX0iuqwrU4FBMqDjckVV" },
      { title: "Wait This Isn't a Fall Themed Piano Song", id: "6l5tCLOJXuK3afkGhRnq4X" },
      { title: "The Leaves Are Still...", id: "0G867D3lYliBJqcvH3AvWr" },
    ],
  },
  {
    album: "Stuck in an Elevator",
    albumId: "0okNaeeNuMjItdHkCOffcM",
    tracks: [
      { title: "Void", id: "6N5Y3ZBetrd4o7O7XgK33Q" },
      { title: "See You Later", id: "640MMkE9m9Ov7g8PLzLfrI" },
      { title: "Sleeping Forever", id: "0cpUc2uxhdTNtxnny6ISvs" },
      { title: "Can't Get You out of My Head", id: "4bJYm4jR9aOTcHTGpY3RJK" },
      { title: "Friends", id: "2cdmcZCrevm0syFC6kMfqL" },
      { title: "Innocence", id: "1kgxUfXFzvM1efwPrICNVc" },
      { title: "Fire in the Elevator", id: "66L9PR5P0WydgJNKtojLVs" },
      { title: "Life Away from Sadness", id: "4k7IgvZ4YqjrVj7gmsPXNu" },
      { title: "Drippy Cave", id: "5BRtGyURsm9LUlB3mAzER5" },
      { title: "Don't Jump", id: "4aNL7Y8sojidmwHpjhCmhB" },
      { title: "Rejected", id: "6RuEDXHGcGD0a37ymv9sIB" },
      { title: "Ring Doorbell", id: "2crI9oMJFIbF3n6nCaTaPw" },
      { title: "Escape", id: "2XNI4hBmHoALDqYPBaNihd" },
      { title: "Without Feeling", id: "55MAOlprUy5lkMmFeypvcI" },
      { title: "Last One", id: "3lS6mKaNZZn8ZGqqvOx09h" },
    ],
  },
  {
    album: "Fleeting Emotions",
    albumId: "2qAbhf7WbynitEpIJIiACR",
    tracks: [
      { title: "Reflecting on Life", id: "1lDfdawaPGcLRgs23wXhNY" },
      { title: "An August Evening", id: "6xMBy6ZolHOGCppJHtgYaw" },
      { title: "Thinking About the Future", id: "4QFjz8Yr7xbYVuINE8ayS1" },
      { title: "Waiting for You", id: "4uv1WAMp9SdBXBC090oZv3" },
      { title: "Nostalgia", id: "1C1W1BtUlCZGN8S87rwDhM" },
      { title: "Raindrops on My Window", id: "5SaxnQFW0wgLxTb57dZKfd" },
      { title: "Don't Look Back", id: "7e3J9pHxut3fsJZ4AiNTzj" },
      { title: "The Sound of Your Voice", id: "5K4m3NidYOGe15vrWvtw1w" },
      { title: "Moonlight Waltz", id: "0pTuYm4I2SwbFUSF2ohuNJ" },
    ],
  },
];
