// ---------------------------------------------------------------------------
// LOADER — do not edit this file.
//
// To change the About page text, open  about.md  (right next to this file)
// and write there. This file just reads that plain writing file and turns it
// into the data the page renders. It is parsed once at build time.
// ---------------------------------------------------------------------------

import fs from "fs";
import path from "path";

export type AboutContent = {
  eyebrow: string;
  heading: string;
  subtitle: string;
  paragraphs: string[];
  facts: { label: string; value: string }[];
};

function splitField(line: string): { key: string; value: string } | null {
  const idx = line.indexOf(":");
  if (idx === -1) return null;
  return { key: line.slice(0, idx).trim(), value: line.slice(idx + 1).trim() };
}

function parse(raw: string): AboutContent {
  const headerLines: string[] = [];
  const bodyLines: string[] = [];
  const factLines: string[] = [];
  let zone: "header" | "body" | "facts" = "header";

  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (/^===\s*BODY\s*===$/i.test(t)) {
      zone = "body";
      continue;
    }
    if (/^===\s*FACTS\s*===$/i.test(t)) {
      zone = "facts";
      continue;
    }
    if (t.startsWith("#")) continue; // comment / note to self
    if (zone === "header") headerLines.push(line);
    else if (zone === "body") bodyLines.push(line);
    else factLines.push(line);
  }

  const field = (key: string): string => {
    for (const l of headerLines) {
      const parsed = splitField(l.trim());
      if (parsed && parsed.key.toLowerCase() === key.toLowerCase()) {
        return parsed.value;
      }
    }
    return "";
  };

  // Blank line = paragraph break. Soft line wraps inside a paragraph collapse
  // to single spaces, so the writer can hard-wrap without it mattering.
  const paragraphs = bodyLines
    .join("\n")
    .split(/\n\s*\n/)
    .map((p) => p.replace(/\s*\n\s*/g, " ").trim())
    .filter(Boolean);

  const facts = factLines
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => splitField(l))
    .filter((f): f is { key: string; value: string } => !!f && !!f.key && !!f.value)
    .map((f) => ({ label: f.key, value: f.value }));

  return {
    eyebrow: field("Eyebrow") || "About",
    heading: field("Heading"),
    subtitle: field("Subtitle"),
    paragraphs,
    facts,
  };
}

const raw = fs.readFileSync(
  path.join(process.cwd(), "src", "content", "about.md"),
  "utf8"
);

export const ABOUT: AboutContent = parse(raw);
